version: '3.4'
services:
  onionsozluk.api.webapi:
    image: onionsozlukapiwebapi
    build:
      context: .
      dockerfile: src/Api/WebApi/OnionSozluk.Api.WebApi/Dockerfile
  onionsozluk.webapp:
    image: onionsozlukwebapp
    build:
      context: .
      dockerfile: src/Clients/BlazorWeb/OnionSozluk.WebApp/Dockerfile
  onionsozluk.projections.favoriteservice:
    image: onionsozlukprojectionsfavoriteservice
    build:
      context: .
      dockerfile: src/Projections/OnionSozluk.Projections.FavoriteService/Dockerfile
  onionsozluk.projections.userservice:
    image: onionsozlukprojectionsuserservice
    build:
      context: .
      dockerfile: src/Projections/OnionSozluk.Projections.UserService/Dockerfile
  onionsozluk.projections.voteservice:
    image: onionsozlukprojectionsvoteservice
    build:
      context: .
      dockerfile: src/Projections/OnionSozluk.Projections.VoteService/Dockerfile
networks:
  blazor_backend:
    driver: bridge
    external: true
  blazor_frontend:
    driver: bridge
    external: true