version: '3.4'
services:
  onionsozluk.api.webapi:
    container_name: "onionsozluk.api.webapi"
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OnionSozlukDbConnectionDbContext=Server=sql_external,1433;Database=onion_sozluk;User Id=sa;Password=Password12*;TrustServerCertificate=true
    ports:
      - "5001:80"
    networks:
      - blazor_backend
      - blazor_frontend
  onionsozluk.webapp:
    container_name: "onionwebapp"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RequestUrl=onionsozluk.api.webapi
    ports:
      - "5000:80"
    networks:
      - blazor_frontend
  onionsozluk.projections.favoriteservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings:SqlServer=Server=sql_external,1433;Database=onion_sozluk;User Id=sa;Password=Password12*;TrustServerCertificate=true
    restart: on-failure
    networks:
      - blazor_backend
  onionsozluk.projections.userservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings:SqlServer=Server=sql_external,1433;Database=onion_sozluk;User Id=sa;Password=Password12*;TrustServerCertificate=true
    restart: on-failure
    networks:
      - blazor_backend
  onionsozluk.projections.voteservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings:SqlServer=Server=sql_external,1433;Database=onion_sozluk;User Id=sa;Password=Password12*;TrustServerCertificate=true
    restart: on-failure
    networks:
      - blazor_backend